### ISSUE TITLE
What is official QEMU port for LoongArch

### ISSUE THREAD

**Issue by kant2002** [sunhaiyong1978/CLFS-for-LoongArch#10]
I see that in your document references https://github.com/gaosong-loongson/qemu
and there https://github.com/loongson/qemu which seems quite close to master. Can you tell what's the differences?

**Comment by sunhaiyong1978** [comment]
https://github.com/gaosong-loongson/qemu是早期支持LoongArch的仓库，目前已经合并到 https://github.com/loongson/qemu了。

**Comment by kant2002** [comment]
Thanks!

**Comment by kant2002** [comment]
Would you mind look at PR #16 where I update link to more recent version of repository. I'm trying to cleanup small issues which I notice during translation. Are you fine with accepting these kind of suggestions?

**Comment by sunhaiyong1978** [comment]
好的，我近期正在更新文档，我会检查相关的修改。
