### ISSUE TITLE
Does autodetection failure means that sometihng should be upstreamed too

### ISSUE THREAD

**Issue by kant2002** [sunhaiyong1978/CLFS-for-LoongArch#13]
I notice that you suggest changing cached configuration values due to detection logic errors. Like this 

https://github.com/sunhaiyong1978/CLFS-for-LoongArch/blob/cfffcf0dca3b310ff3bb92ba7d7a6bc91e3f66fd/CLFS_For_LoongArch64-20210903.md#L803-L808

Isn't this means that some configuration logic should be upstreamed first? That way for building LoongArch64 applications you don't have to make these  changes everywhere.

**Comment by sunhaiyong1978** [comment]
这些参数是因为交叉编译的情况下无法探测或者探测错误，因此需要进行指定，对于交叉编译这是一种常规手段，如果是本地编译则没有问题。

**Comment by kant2002** [comment]
Thanks for clarification. The document is a bit dense for newcomer, so I have silly questions.
