### ISSUE TITLE
gcc 编译器问题 internal compiler error: in output_constructor_regular_field, at varasm.c:5512

### ISSUE THREAD

**Issue by redeastcn** [sunhaiyong1978/CLFS-for-LoongArch#17]
孙老师，您好！我在用您的2.3版CLFS的GCC 编译 poppler时，会出错，编译QT5.15也报同样的错误。麻烦看看是什么原因。谢谢！

 g++ poppler_Decrypt_preprocessed.cc -c
/var/tmp/portage/app-text/poppler-21.12.0/work/poppler-21.12.0/poppler/Decrypt.cc:1826:1: 编译器内部错误：在 output_constructor_regular_field 中，于 varasm.c:5512
 1826 | }
      | ^
0x1134277 internal_error(char const*, ...)
        ???:0
0x1a2887 fancy_abort(char const*, int, char const*)
        ???:0
0xbdecbf assemble_variable(tree_node*, int, int, int)
        ???:0
0xbe24ab varpool_node::assemble_decl()
        ???:0
0x4c2067 symbol_table::finalize_compilation_unit()
        ???:0
请提交一份完整的错误报告，
如有可能请附上经预处理后的源文件。
Please include the complete backtrace with any bug report.

**Comment by sunhaiyong1978** [comment]
编译器错误?要不等下一版更新编译器后再试试？或者跟https://github.com/loongson/gcc报一下。

**Comment by redeastcn** [comment]
好的，谢谢回复！
