### ISSUE TITLE
关于目标系统 GCC 的链接问题

### ISSUE THREAD

**Issue by xyq1113723547** [sunhaiyong1978/CLFS-for-LoongArch#2]
孙老师你好，
在为目标系统编译安装GCC后，有这么一行命令：
```
ln -sv /usr/bin/cpp ${SYSDIR}/sysroot/lib
```
个人认为这是笔误，还望指正。

**Comment by sunhaiyong1978** [comment]
你觉得哪不对？

**Comment by xyq1113723547** [comment]
软链接会指向当前 `/usr/bin/cpp`，如最终用 CLFS 引导启动，这软链接没有问题。只是目前本人是用 3A5000 机器编译，在构建最后一遍 GCC 后没有 chroot 进 CLFS ，而是直接测试，就导致用了宿主 Loongnix 20 的 cpp。
