### ISSUE TITLE
v20220108 duo le yi ge 3.15

### ISSUE THREAD

**Issue by redeastcn** [sunhaiyong1978/CLFS-for-LoongArch#23]
3.15 Jinja

tar xvf ${DOWNLOADDIR}/Jinja2-3.0.3.tar.gz -C ${BUILDDIR}
pushd ${BUILDDIR}/Jinja2-3.0.3
    python3 setup.py install --optimize=1
popd

**Comment by sunhaiyong1978** [comment]
嗯，编号漏改了。

**Comment by sunhaiyong1978** [comment]
嗯，多了一个，下版删掉
