### ISSUE TITLE
V20220108 biwu

### ISSUE THREAD

**Issue by redeastcn** [sunhaiyong1978/CLFS-for-LoongArch#25]
- tar xvf ${DOWNLOADDIR}/binutils-2.37.tar.xz -C ${BUILDDIR}
+ tar xvf ${DOWNLOADDIR}/binutils-2.37.tar.gz -C ${BUILDDIR}

**Comment by sunhaiyong1978** [comment]
收到，谢谢

**Comment by redeastcn** [comment]
谢谢孙老师的教程，让我们受益匪浅！
