### ISSUE TITLE
缺少补丁文件

### ISSUE THREAD

**Issue by cnsyzxj** [sunhaiyong1978/CLFS-for-LoongArch#45]
没有找到文档中提到的如下补丁文件：

guile-3.0.8-add-loongarch64.patch
rustc-1.65.0-add-loongarch-support.patch
cmake-3.22.3-add-loongarch64-to-checktypesize.patch
cmake-3.22.3-add-loongarch64-to-checktypesize.patch
0001-gdb-gdbserver-LoongArch-Improve-implementation-of-fc.patch
userspace-rcu-0.13.1-add-loongarch64.patch
0001-Rustc-1.67.1-vendor-linux-raw-sys-add-loongarch64.patch
xorg-server-21.1.3-fix-x11perf-segment-fault.patch
gstreamer-1.20.0-add-loongarch64.patch
0001-librsvg-2.54.5-fix-loongarch64-support.patch
0001-mozjs-91-add-loongarch64-supprot.patch
qt-everywhere-src-5.15.2-add-loongarch-config.patch
qt-everywhere-src-5.15.6-fix-for-gcc13.patch
0001-QT-5.15.8-add-loongarch64-support.patch
sip-add-loongarch64.patch
pyqt-5.15.6-cross_compiler.patch
pyqt-5.15.6-fix-sip.patch
0001-ibus-1.5.28-change-for-cross-compiler.patch
firefox-100-add-loongarch.patch
firefox-110-fix-rust.patch
firefox-100-xpcom-add-loongarch.patch
firefox-100-for-clfs.patch
firefox-105-fix-for-gcc13.patch
firefox-105-fix-jit-for-loongarch64.patch

**Comment by sunhaiyong1978** [comment]
补丁已补全，可参考最新的文档及patches目录。
