### ISSUE TITLE
8.0工具链std::function无法使用

### ISSUE THREAD

**Issue by prcups** [sunhaiyong1978/CLFS-for-LoongArch#47]
使用8.0工具链时，哪怕#include <functional> 也会提示找不到std::function，并给出令人哭笑不得的修复建议。

![](https://krgm.moe/static/upload_images/csgrtkj6h0uhaulcej.png)

使用6.0版本不会有此问题。

**Comment by sunhaiyong1978** [comment]
你试试指定一个早一些的C++标准来编译看看？比如c++14?

**Comment by Mo01iHt** [comment]
Hi @prcups , I have similar problems. How did you fix this issue? Can you give me some solutions, please. thx.
