### ISSUE TITLE
请教在x86平台使用qemu运行商业版（旧世界）loongarch64的方法

### ISSUE THREAD

**Issue by latelee** [sunhaiyong1978/CLFS-for-LoongArch#53]
孙老师好！
我最近研究x86平台运行loongarch64系统的方法，遇到一些问题，向您请教。

1、需求
我有一台龙芯3A6000的机器，安装了商业版本的kylin linux发行版。因为机器上编译程序较麻烦，因此考虑在x86服务器上运行龙芯的编译环境，由于业务程序较复杂，无法使用交叉编译的方法，因此考虑用qemu模拟。

2、clfs的实验
我下载了 loongarch64-clfs-system-20210903.tar.bz2和qemu-x86_64-to-loongarch64，按老师的教程实验，用chroot切换，能正常运行，查看内核看到`loongarch64`：
```
bash-5.1# uname -a
Linux localhost.localdomain 4.19.0 #1 SMP Mon Oct 19 16:18:59 UTC 2020 loongarch64 GNU/Linux
```

3、kylin发行版的实验
我使用商业发行版kylin的ISO安装镜像，解压了filesystem.squashfs，得到squashfs-root，按教程进行chroot，但即时退出了：
```
# chroot squashfs-root
root@localhost:/# exit
```
开启了qemu跟踪，最后的出错信息如下：
```
188261 rt_sigprocmask(SIG_BLOCK,0x0000000120119a88,0x000000012011fdc0) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGINT,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGTERM,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGHUP,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGQUIT,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGALRM,0x0000004000801ca8,0x0000004000801d38) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(20,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGTTOU,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGTTIN,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigprocmask(SIG_SETMASK,0x000000012011fdc0,NULL) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(28,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 fstat(2,0x0000004000801c78) = 0
root@localhost:/# 188261 write(2,0x2016a150,18) = 18
188261 pselect6(1,274886303432,0,0,0,274886303368) = -1 errno=22 (Invalid argument)
188261 ioctl(0,TCGETS,0x0000004000801f80) = 0 ({c_iflag = IXON,c_oflag = OPOST|ONLCR,c_cflag = B38400,CS8,CREAD,c_lflag = ISIG|ECHOE|ECHOK|ECHOCTL|ECHOKE|IEXTEN,c_cc = "",c_line = ''})
188261 ioctl(0,TCSETSW,{c_iflag = ICRNL|IXON,c_oflag = OPOST|ONLCR,c_cflag = B38400,CS8,CREAD,c_lflag = ISIG|ICANON|ECHO|ECHOE|ECHOK|ECHOCTL|ECHOKE|IEXTEN,c_cc = "",c_line = ''}) = 0
188261 ioctl(0,TCGETS,0x0000004000801f58) = 0 ({c_iflag = ICRNL|IXON,c_oflag = OPOST|ONLCR,c_cflag = B38400,CS8,CREAD,c_lflag = ISIG|ICANON|ECHO|ECHOE|ECHOK|ECHOCTL|ECHOKE|IEXTEN,c_cc = "",c_line = ''})
188261 rt_sigaction(SIGINT,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGTERM,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGHUP,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGQUIT,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGALRM,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(20,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGTTOU,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGTTIN,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(28,0x0000004000801e18,0x0000004000801ea8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGINT,0x0000004000801d88,0x0000004000801e18) = -1 errno=22 (Invalid argument)
exit
188261 write(2,0x2016a150,5) = 5
188261 rt_sigaction(SIGINT,0x0000004000802e58,0x0000004000802ee8) = -1 errno=22 (Invalid argument)
188261 rt_sigprocmask(SIG_BLOCK,0x0000004000802ff8,0x0000004000803078) = -1 errno=22 (Invalid argument)
188261 rt_sigprocmask(SIG_SETMASK,0x0000004000803078,NULL) = -1 errno=22 (Invalid argument)
188261 setpgid(0,188261) = 0
188261 exit_group(0)
```
4、问题
使用qemu-x86_64-to-loongarch64切换kylin的rootfs会提示`Invalid argument`，怀疑是新旧世界兼容性的问题。
我的业务需求是模拟旧世界的环境，这块在网上资料较少。
请问，孙老师有什么建议或思路吗？谢谢！

另：我试了qemu官方https://github.com/multiarch/qemu-user-static/releases 的v7.2.0-1 版本，没有提示`Invalid argument`，但提示`/bin/bash: error while loading shared libraries: libtinfo.so.6: cannot stat shared object: Error 38`

**Comment by sunhaiyong1978** [comment]
你用的Kylin使用的是LoongArch 的 ABI 1.0标准，而目前网上提供的CLFS系统使用的是 ABI 2.0标准，这两个标准存在相互不兼容的情况，所以不能混用。另外网上提供的qemu-loongarch64也同样是使用ABI 2.0的标准提供的。
所以当想使用ABI 1.0做开发最好还是在目标系统里进行编译，如果非要使用交叉方式可以 https://www.loongnix.cn/zh/toolchain/GNU/ 这里下载ABI 1.0的交叉工具链来使用。

----- Original Message -----
From: Late Lee ***@***.***>
To: sunhaiyong1978/CLFS-for-LoongArch ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sunhaiyong1978/CLFS-for-LoongArch]_请教在x86平台使用qemu运行商业版（旧世界）loongarch64的方法_(Issue_#53)
Date: 2024-11-25 09:55


孙老师好！

我最近研究x86平台运行loongarch64系统的方法，遇到一些问题，向您请教。
1、需求

我有一台龙芯3A6000的机器，安装了商业版本的kylin linux发行版。因为机器上编译程序较麻烦，因此考虑在x86服务器上运行龙芯的编译环境，由于业务程序较复杂，无法使用交叉编译的方法，因此考虑用qemu模拟。
2、clfs的实验

我下载了 loongarch64-clfs-system-20210903.tar.bz2和qemu-x86_64-to-loongarch64，按老师的教程实验，用chroot切换，能正常运行，查看内核看到loongarch64：
bash-5.1# uname -a
Linux localhost.localdomain 4.19.0 #1 SMP Mon Oct 19 16:18:59 UTC 2020 loongarch64 GNU/Linux

3、kylin发行版的实验

我使用商业发行版kylin的ISO安装镜像，解压了filesystem.squashfs，得到squashfs-root，按教程进行chroot，但即时退出了：
# chroot squashfs-root
***@***.***:/# exit

开启了qemu跟踪，最后的出错信息如下：
188261 rt_sigprocmask(SIG_BLOCK,0x0000000120119a88,0x000000012011fdc0) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGINT,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGTERM,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGHUP,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGQUIT,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGALRM,0x0000004000801ca8,0x0000004000801d38) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(20,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGTTOU,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGTTIN,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 rt_sigprocmask(SIG_SETMASK,0x000000012011fdc0,NULL) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(28,0x0000004000801bd8,0x0000004000801c68) = -1 errno=22 (Invalid argument)
188261 fstat(2,0x0000004000801c78) = 0
***@***.***:/# 188261 write(2,0x2016a150,18) = 18
188261 pselect6(1,274886303432,0,0,0,274886303368) = -1 errno=22 (Invalid argument)
188261 ioctl(0,TCGETS,0x0000004000801f80) = 0 ({c_iflag = IXON,c_oflag = OPOST|ONLCR,c_cflag = B38400,CS8,CREAD,c_lflag = ISIG|ECHOE|ECHOK|ECHOCTL|ECHOKE|IEXTEN,c_cc = "",c_line = ''})
188261 ioctl(0,TCSETSW,{c_iflag = ICRNL|IXON,c_oflag = OPOST|ONLCR,c_cflag = B38400,CS8,CREAD,c_lflag = ISIG|ICANON|ECHO|ECHOE|ECHOK|ECHOCTL|ECHOKE|IEXTEN,c_cc = "",c_line = ''}) = 0
188261 ioctl(0,TCGETS,0x0000004000801f58) = 0 ({c_iflag = ICRNL|IXON,c_oflag = OPOST|ONLCR,c_cflag = B38400,CS8,CREAD,c_lflag = ISIG|ICANON|ECHO|ECHOE|ECHOK|ECHOCTL|ECHOKE|IEXTEN,c_cc = "",c_line = ''})
188261 rt_sigaction(SIGINT,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGTERM,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGHUP,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGQUIT,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGALRM,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(20,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGTTOU,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGTTIN,0x0000004000801d58,0x0000004000801de8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(28,0x0000004000801e18,0x0000004000801ea8) = -1 errno=22 (Invalid argument)
188261 rt_sigaction(SIGINT,0x0000004000801d88,0x0000004000801e18) = -1 errno=22 (Invalid argument)
exit
188261 write(2,0x2016a150,5) = 5
188261 rt_sigaction(SIGINT,0x0000004000802e58,0x0000004000802ee8) = -1 errno=22 (Invalid argument)
188261 rt_sigprocmask(SIG_BLOCK,0x0000004000802ff8,0x0000004000803078) = -1 errno=22 (Invalid argument)
188261 rt_sigprocmask(SIG_SETMASK,0x0000004000803078,NULL) = -1 errno=22 (Invalid argument)
188261 setpgid(0,188261) = 0
188261 exit_group(0)

4、问题

使用qemu-x86_64-to-loongarch64切换kylin的rootfs会提示Invalid argument，怀疑是新旧世界兼容性的问题。

我的业务需求是模拟旧世界的环境，这块在网上资料较少。

请问，孙老师有什么建议或思路吗？谢谢！
另：我试了qemu官方https://github.com/multiarch/qemu-user-static/releases 的v7.2.0-1 版本，没有提示Invalid argument，但提示/bin/bash: error while loading shared libraries: libtinfo.so.6: cannot stat shared object: Error 38

**Comment by latelee** [comment]
感谢孙老师回复，我的问题如您所说。因为一些原因，龙芯官方交叉编译器不适用。这个问题，我还得再研究研究。
